### PR TITLE
Change license to the simpler MIT

### PR DESCRIPTION
**Pull request by pajlada**
I would like to change the license of pajbot2 from LGPL-3 to MIT

I'd like a sign-off from any previous contributors, so if you could comment below with your approval, disapproval, or comments, that would be appreciated

@nuuls 
@gempir 
@fourtf 
@dankeroni

### CODE REVIEW

**Comment by fourtf** [comment]
Approved

**Comment by nuuls** [comment]
Approved

**Comment by dankeroni** [comment]
Approved

**Comment by pajlada** [comment]
Full approval so I will go ahead and merge this, thanks!

**Pull request merged**
